# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/frankie/WCIS/WCIS-CMODA7-Control-Board/sw/root/fw/updated_adc_operation_and_dac_works_frankie/updated_adc_operation_and_dac_works_frankie.srcs/sources_1/ip/rx_fifo/rx_fifo.xci
# IP: The module: 'rx_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/frankie/WCIS/WCIS-CMODA7-Control-Board/sw/root/fw/updated_adc_operation_and_dac_works_frankie/updated_adc_operation_and_dac_works_frankie.gen/sources_1/ip/rx_fifo/rx_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'rx_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/frankie/WCIS/WCIS-CMODA7-Control-Board/sw/root/fw/updated_adc_operation_and_dac_works_frankie/updated_adc_operation_and_dac_works_frankie.gen/sources_1/ip/rx_fifo/rx_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/frankie/WCIS/WCIS-CMODA7-Control-Board/sw/root/fw/updated_adc_operation_and_dac_works_frankie/updated_adc_operation_and_dac_works_frankie.srcs/sources_1/ip/rx_fifo/rx_fifo.xci
# IP: The module: 'rx_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/frankie/WCIS/WCIS-CMODA7-Control-Board/sw/root/fw/updated_adc_operation_and_dac_works_frankie/updated_adc_operation_and_dac_works_frankie.gen/sources_1/ip/rx_fifo/rx_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'rx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/frankie/WCIS/WCIS-CMODA7-Control-Board/sw/root/fw/updated_adc_operation_and_dac_works_frankie/updated_adc_operation_and_dac_works_frankie.gen/sources_1/ip/rx_fifo/rx_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
