# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/frankie/WCIS/WCIS-CMODA7-Control-Board/ROOT/wcis_adc_control/wcis_adc_control.srcs/sources_1/ip/tx_fifo/tx_fifo.xci
# IP: The module: 'tx_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/frankie/WCIS/WCIS-CMODA7-Control-Board/ROOT/wcis_adc_control/wcis_adc_control.gen/sources_1/ip/tx_fifo/tx_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'tx_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/frankie/WCIS/WCIS-CMODA7-Control-Board/ROOT/wcis_adc_control/wcis_adc_control.gen/sources_1/ip/tx_fifo/tx_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/frankie/WCIS/WCIS-CMODA7-Control-Board/ROOT/wcis_adc_control/wcis_adc_control.srcs/sources_1/ip/tx_fifo/tx_fifo.xci
# IP: The module: 'tx_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/frankie/WCIS/WCIS-CMODA7-Control-Board/ROOT/wcis_adc_control/wcis_adc_control.gen/sources_1/ip/tx_fifo/tx_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'tx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/frankie/WCIS/WCIS-CMODA7-Control-Board/ROOT/wcis_adc_control/wcis_adc_control.gen/sources_1/ip/tx_fifo/tx_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
