# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/frankie/WCIS/FLASH-ADC-CHARACTERIZATION/vivado projects/adc_control_schanchain_and_adctop/adc_control_schanchain_and_adctop.srcs/sources_1/ip/clk_wiz_base/clk_wiz_base.xci
# IP: The module: 'clk_wiz_base' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/frankie/WCIS/FLASH-ADC-CHARACTERIZATION/vivado projects/adc_control_schanchain_and_adctop/adc_control_schanchain_and_adctop.gen/sources_1/ip/clk_wiz_base/clk_wiz_base_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_base'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/frankie/WCIS/FLASH-ADC-CHARACTERIZATION/vivado projects/adc_control_schanchain_and_adctop/adc_control_schanchain_and_adctop.gen/sources_1/ip/clk_wiz_base/clk_wiz_base.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_base'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/frankie/WCIS/FLASH-ADC-CHARACTERIZATION/vivado projects/adc_control_schanchain_and_adctop/adc_control_schanchain_and_adctop.gen/sources_1/ip/clk_wiz_base/clk_wiz_base_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_base'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/frankie/WCIS/FLASH-ADC-CHARACTERIZATION/vivado projects/adc_control_schanchain_and_adctop/adc_control_schanchain_and_adctop.srcs/sources_1/ip/clk_wiz_base/clk_wiz_base.xci
# IP: The module: 'clk_wiz_base' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/frankie/WCIS/FLASH-ADC-CHARACTERIZATION/vivado projects/adc_control_schanchain_and_adctop/adc_control_schanchain_and_adctop.gen/sources_1/ip/clk_wiz_base/clk_wiz_base_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_base'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/frankie/WCIS/FLASH-ADC-CHARACTERIZATION/vivado projects/adc_control_schanchain_and_adctop/adc_control_schanchain_and_adctop.gen/sources_1/ip/clk_wiz_base/clk_wiz_base.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_base'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/frankie/WCIS/FLASH-ADC-CHARACTERIZATION/vivado projects/adc_control_schanchain_and_adctop/adc_control_schanchain_and_adctop.gen/sources_1/ip/clk_wiz_base/clk_wiz_base_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_base'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
